ALTER TABLE production_products
    ADD COLUMN IF NOT EXISTS base_price NUMERIC(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS min_discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS min_selling_price NUMERIC(18,2) NOT NULL DEFAULT 0;
