ALTER TABLE finished_goods
    ADD COLUMN IF NOT EXISTS revenue_account_id BIGINT,
    ADD COLUMN IF NOT EXISTS discount_account_id BIGINT,
    ADD COLUMN IF NOT EXISTS tax_account_id BIGINT;

ALTER TABLE sales_orders
    ADD COLUMN IF NOT EXISTS subtotal_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gst_total NUMERIC(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gst_treatment VARCHAR(32) NOT NULL DEFAULT 'NONE',
    ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(7,4),
    ADD COLUMN IF NOT EXISTS gst_rounding_adjustment NUMERIC(18,2) NOT NULL DEFAULT 0;

ALTER TABLE sales_order_items
    ADD COLUMN IF NOT EXISTS line_subtotal NUMERIC(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS line_total NUMERIC(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(7,4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gst_amount NUMERIC(18,2) NOT NULL DEFAULT 0;
